language: rust
notifications:
    irc: "irc.mozilla.org#piston-internals"
os:
    - linux
    - osx
before_install:
    - sudo apt-get update -qq
install:
    - sudo apt-get install libfreetype6-dev libXxf86vm-dev
script:
    - cd ./getting-started
    - cargo build -v
