[package]

name = "getting-started-spinning-square"
version = "0.1.0"
authors = [
    "TyOverby <ty@pre-alpha.com>",
    "Nikita Pekin <contact@nikitapek.in>"
]

[[bin]]
name = "spinning-square"

[dependencies]
piston = "0.10.0"
piston2d-graphics = "0.7.1"
pistoncore-glutin_window = "0.12.0"
piston2d-opengl_graphics = "0.9.0"
